version: '3'
services:
  coordination:
    image: coordination
    network_mode: host
    restart: always
    ports:
      - 5000:5000
  suivrelumieres:
    image: suivrelumieres
    restart: always
    network_mode: host
    ports:
      - 5100:5100
  evitementobstacles:
    image: evitementobstacles
    restart: always
    network_mode: host
    ports:
      - 5200:5200
