version: '3'
services:
  coordination:
    image: coordination
    network_mode: host
    restart: always
    ports:
      - 5000:5000
  suivrelumieres:
    image: suivrelumieres
    restart: always
    links:
      - coordination
    ports:
      - 5100:5100
